name: Deploy Dev
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  deployments: read
  id-token: write
jobs:
  deploy:
    if: vars.GCP_DEPLOY_ENABLED == 'true' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      target_environment: dev
